# Generated by Django 5.2.15 on 2026-06-17 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='business_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verification_document',
            field=models.ImageField(blank=True, null=True, upload_to='verification_documents/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verification_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verification_status',
            field=models.CharField(choices=[('not_requested', 'Not Requested'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_requested', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
