# Generated by Django 5.2.15 on 2026-06-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='seller_messaging_block_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='seller_messaging_blocked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='seller_suspended_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='seller_suspension_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='seller_warning_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userreport',
            name='action_taken',
            field=models.CharField(choices=[('none', 'No action'), ('reviewed', 'Marked reviewed'), ('dismissed', 'Dismissed'), ('warned_seller', 'Warned seller'), ('suspended_seller', 'Suspended seller'), ('removed_verification', 'Removed verification'), ('archived_listings', 'Archived seller listings'), ('blocked_messaging', 'Blocked seller messaging')], default='none', max_length=40),
        ),
        migrations.AddField(
            model_name='userreport',
            name='action_taken_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userreport',
            name='reporter_note',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
