# Generated by Django 5.2.15 on 2026-06-17 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_seller_messaging_block_reason_and_more'),
        ('listings', '0011_listingreport_action_taken_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField()),
                ('notice_type', models.CharField(choices=[('report_update', 'Report update'), ('listing_action', 'Listing action'), ('seller_action', 'Seller action')], default='report_update', max_length=40)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_notices', to='listings.listing')),
                ('listing_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_notices', to='listings.listingreport')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_notices', to=settings.AUTH_USER_MODEL)),
                ('user_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_notices', to='accounts.userreport')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
