# Generated by Django 5.2.15 on 2026-06-18 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_moderationappealattachment'),
        ('listings', '0012_listing_status_before_seller_suspension_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustSafetyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('listing_report_reviewed', 'Listing report reviewed'), ('listing_suspended', 'Listing suspended'), ('listing_archived', 'Listing archived'), ('listing_restored', 'Listing restored'), ('seller_report_reviewed', 'Seller report reviewed'), ('seller_warned', 'Seller warned'), ('seller_suspended', 'Seller suspended'), ('seller_suspension_lifted', 'Seller suspension lifted'), ('seller_verification_removed', 'Seller verification removed'), ('seller_listings_archived', 'Seller listings archived'), ('seller_messaging_blocked', 'Seller messaging blocked'), ('appeal_submitted', 'Appeal submitted'), ('appeal_approved', 'Appeal approved'), ('appeal_rejected', 'Appeal rejected'), ('appeal_reopened', 'Appeal reopened'), ('notice_sent', 'Notice sent'), ('audit_repair', 'Audit repair')], db_index=True, max_length=80)),
                ('title', models.CharField(max_length=255)),
                ('public_note', models.TextField(blank=True, default='')),
                ('internal_note', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trust_safety_events_performed', to=settings.AUTH_USER_MODEL)),
                ('appeal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trust_safety_events', to='accounts.moderationappeal')),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trust_safety_events', to='listings.listing')),
                ('listing_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trust_safety_events', to='listings.listingreport')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trust_safety_events_about', to=settings.AUTH_USER_MODEL)),
                ('user_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trust_safety_events', to='accounts.userreport')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='accounts_tr_event_t_e87c3b_idx'), models.Index(fields=['actor', 'created_at'], name='accounts_tr_actor_i_542935_idx'), models.Index(fields=['target_user', 'created_at'], name='accounts_tr_target__258136_idx')],
            },
        ),
    ]
