# Generated by Django 5.2.15 on 2026-06-19 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_trustsafetyevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='moderationappeal',
            name='extra_evidence_fulfilled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moderationappeal',
            name='extra_evidence_request_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='moderationappeal',
            name='extra_evidence_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moderationappeal',
            name='extra_evidence_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_appeal_extra_evidence_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
