# Generated by Django 5.2.15 on 2026-06-19 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_moderationappeal_extra_evidence_fulfilled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderationappeal',
            name='extra_evidence_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
