# Generated by Django 5.2.15 on 2026-06-19 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_moderationappeal_extra_evidence_due_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderationappeal',
            name='extra_evidence_overdue_notice_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moderationappeal',
            name='extra_evidence_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
