# Generated by Django 5.2.15 on 2026-06-19 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_moderationappeal_extra_evidence_overdue_notice_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderationappealattachment',
            name='evidence_stage',
            field=models.CharField(choices=[('initial', 'Initial appeal evidence'), ('extra', 'Extra evidence')], default='initial', max_length=20),
        ),
    ]
