# Generated by Django 5.2.15 on 2026-06-17 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_listingpromotion_paid_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingpromotion',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='promotion_payment_proofs/'),
        ),
    ]
