# Generated by Django 5.2.15 on 2026-06-17 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_listingpromotion_payment_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingpromotion',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
