# Generated by Django 5.2.15 on 2026-07-24 06:21

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0025_notification_delivery_retention_v308'),
        ('promotions', '0004_alter_listingpromotion_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listingpromotion',
            name='discount_percent_snapshot',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=5),
        ),
        migrations.AddField(
            model_name='listingpromotion',
            name='duration_mode_snapshot',
            field=models.CharField(blank=True, choices=[('fixed_weeks', 'Fixed Weeks'), ('listing_lifetime', 'Listing Lifetime'), ('single_use', 'Single Use')], default='', max_length=24),
        ),
        migrations.AddField(
            model_name='listingpromotion',
            name='price_group_snapshot',
            field=models.CharField(blank=True, choices=[('real_estate', 'Real Estate'), ('vehicles', 'Vehicles'), ('vehicle_parts', 'Vehicle Parts'), ('marketplace', 'Marketplace'), ('industrial', 'Industrial'), ('lessons', 'Lessons & Training'), ('jobs', 'Jobs'), ('pets', 'Pets'), ('helpers', 'Helpers Wanted')], default='', max_length=32),
        ),
        migrations.AddField(
            model_name='listingpromotion',
            name='promotion_code_snapshot',
            field=models.CharField(blank=True, choices=[('small_photo', 'Small Photo'), ('urgent', 'Urgent'), ('homepage_showcase', 'Homepage Showcase'), ('category_showcase', 'Category Showcase'), ('top_ranking', 'Top Ranking'), ('detailed_search_showcase', 'Detailed Search Showcase'), ('colorful_title', 'Bold Title & Colorful Frame'), ('refresh', 'Refresh Listing')], default='', max_length=40),
        ),
        migrations.AddField(
            model_name='listingpromotion',
            name='requested_weeks',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listingpromotion',
            name='unit_price_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='promotionpackage',
            name='catalog_code',
            field=models.CharField(blank=True, choices=[('small_photo', 'Small Photo'), ('urgent', 'Urgent'), ('homepage_showcase', 'Homepage Showcase'), ('category_showcase', 'Category Showcase'), ('top_ranking', 'Top Ranking'), ('detailed_search_showcase', 'Detailed Search Showcase'), ('colorful_title', 'Bold Title & Colorful Frame'), ('refresh', 'Refresh Listing')], db_index=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='promotionpackage',
            name='duration_mode',
            field=models.CharField(blank=True, choices=[('fixed_weeks', 'Fixed Weeks'), ('listing_lifetime', 'Listing Lifetime'), ('single_use', 'Single Use')], default='', max_length=24),
        ),
        migrations.AddField(
            model_name='promotionpackage',
            name='price_group',
            field=models.CharField(blank=True, choices=[('real_estate', 'Real Estate'), ('vehicles', 'Vehicles'), ('vehicle_parts', 'Vehicle Parts'), ('marketplace', 'Marketplace'), ('industrial', 'Industrial'), ('lessons', 'Lessons & Training'), ('jobs', 'Jobs'), ('pets', 'Pets'), ('helpers', 'Helpers Wanted')], db_index=True, default='', max_length=32),
        ),
        migrations.AddConstraint(
            model_name='listingpromotion',
            constraint=models.CheckConstraint(condition=models.Q(('requested_weeks__isnull', True), ('requested_weeks__in', (1, 2, 4)), _connector='OR'), name='promo_requested_weeks_valid_v342'),
        ),
        migrations.AddConstraint(
            model_name='listingpromotion',
            constraint=models.CheckConstraint(condition=models.Q(('discount_percent_snapshot__gte', Decimal('0.0000')), ('discount_percent_snapshot__lte', Decimal('1.0000'))), name='promo_discount_snapshot_range_v342'),
        ),
        migrations.AddConstraint(
            model_name='promotionpackage',
            constraint=models.UniqueConstraint(condition=models.Q(('catalog_code', ''), _negated=True), fields=('catalog_code', 'price_group'), name='promo_catalog_group_unique_v342'),
        ),
    ]
