# Generated by Django 5.2.15 on 2026-06-17 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_expires_at_listingfavorite_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='featured_priority',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
