# Generated by Django 5.2.15 on 2026-06-17 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_listing_featured_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='featured_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
