# Generated by Django 5.2.15 on 2026-06-17 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_listing_featured_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='top_listing_priority',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='top_listing_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
