# Generated by Django 5.2.15 on 2026-06-17 11:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_listingreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listingreport',
            name='reasons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='listingreport',
            name='reason',
            field=models.CharField(choices=[('scam', 'Scam or fraud'), ('fake_seller', 'Fake or suspicious seller'), ('misleading', 'Misleading title, description, or photos'), ('incorrect_price', 'Incorrect or suspicious price'), ('not_available', 'Item no longer available'), ('illegal', 'Illegal or restricted item'), ('counterfeit', 'Counterfeit item'), ('offensive', 'Offensive or abusive content'), ('spam', 'Spam'), ('contact_info', 'Contact info or external link in listing'), ('wrong_category', 'Wrong category'), ('prohibited', 'Prohibited item'), ('duplicate', 'Duplicate listing'), ('other', 'Other')], max_length=40),
        ),
        migrations.AddConstraint(
            model_name='listingreport',
            constraint=models.UniqueConstraint(fields=('listing', 'reporter'), name='unique_report_per_user_listing'),
        ),
    ]
