# Generated by Django 5.2.15 on 2026-06-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_listingreport_reasons_alter_listingreport_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingreport',
            name='action_taken',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='listingreport',
            name='reporter_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('archived', 'Archived'), ('suspended', 'Suspended')], default='approved', max_length=20),
        ),
    ]
