# Generated by Django 5.2.15 on 2026-06-18 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_listingreport_action_taken_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='status_before_seller_suspension',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='suspended_due_to_seller',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
