# Generated by Django 5.2.15 on 2026-06-19 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_listing_status_before_seller_suspension_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
