# Generated by Django 5.2.15 on 2026-06-21 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_savedsearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedsearch',
            name='email_notifications_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='last_notification_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedsearch',
            name='last_notification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
