# Generated by Django 5.2.15 on 2026-07-14 01:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_savedsearch_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSearchNotificationAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_id_snapshot', models.CharField(max_length=64)),
                ('event_type', models.CharField(choices=[('evaluation_started', 'Evaluation started'), ('skipped_notifications_disabled', 'Skipped: notifications disabled'), ('skipped_missing_recipient', 'Skipped: missing recipient'), ('dry_run_rendered', 'Dry-run rendered'), ('delivery_attempted', 'Delivery attempted'), ('delivery_succeeded', 'Delivery succeeded'), ('delivery_failed', 'Delivery failed'), ('sent_timestamp_recorded', 'Sent timestamp recorded'), ('rollback_previewed', 'Rollback previewed'), ('rollback_applied', 'Rollback applied')], max_length=64)),
                ('outcome', models.CharField(choices=[('pending', 'Pending'), ('skipped', 'Skipped'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('rolled_back', 'Rolled back')], max_length=32)),
                ('reason_code', models.CharField(blank=True, max_length=96)),
                ('occurred_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch_id', models.UUIDField(blank=True, null=True)),
                ('correlation_id', models.UUIDField()),
                ('delivery_attempt_id', models.UUIDField(blank=True, null=True)),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('notification_fingerprint', models.CharField(max_length=64)),
                ('actor_type', models.CharField(choices=[('system', 'System'), ('scheduler', 'Scheduler'), ('operator', 'Operator'), ('management_command', 'Management command'), ('test_backend', 'Test backend')], max_length=32)),
                ('actor_identifier', models.CharField(blank=True, max_length=128)),
                ('source', models.CharField(max_length=128)),
                ('checked_at_before', models.DateTimeField(blank=True, null=True)),
                ('checked_at_after', models.DateTimeField(blank=True, null=True)),
                ('sent_at_before', models.DateTimeField(blank=True, null=True)),
                ('sent_at_after', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('rollback_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rollback_events', to='listings.savedsearchnotificationauditevent')),
                ('saved_search', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notification_audit_events', to='listings.savedsearch')),
            ],
            options={
                'db_table': 'listings_savedsearchnotificationauditevent',
                'ordering': ('-occurred_at', '-created_at'),
                'get_latest_by': 'occurred_at',
                'indexes': [models.Index(fields=['saved_search', 'occurred_at'], name='ssna_saved_occ_idx'), models.Index(fields=['event_type', 'occurred_at'], name='ssna_event_occ_idx'), models.Index(fields=['outcome', 'occurred_at'], name='ssna_outcome_occ_idx'), models.Index(fields=['batch_id'], name='ssna_batch_idx'), models.Index(fields=['correlation_id'], name='ssna_corr_idx'), models.Index(fields=['delivery_attempt_id'], name='ssna_attempt_idx'), models.Index(fields=['notification_fingerprint'], name='ssna_fingerprint_idx'), models.Index(fields=['rollback_of'], name='ssna_rollback_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('event_type__in', ('rollback_previewed', 'rollback_applied')), _negated=True), ('rollback_of__isnull', False), _connector='OR'), name='ssna_rollback_link_required'), models.CheckConstraint(condition=models.Q(models.Q(('event_type__in', ('delivery_attempted', 'delivery_succeeded', 'delivery_failed')), _negated=True), ('delivery_attempt_id__isnull', False), _connector='OR'), name='ssna_delivery_attempt_required')],
            },
        ),
    ]
