# Generated by Django 5.2.15 on 2026-07-18 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0019_listingpricealert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationDeliveryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('listing_price_drop', 'Listing price drop'), ('saved_search_new_listing', 'Saved-search new listing'), ('saved_search_price_drop', 'Saved-search price drop')], max_length=40)),
                ('channel', models.CharField(default='email', max_length=16)),
                ('event_key', models.CharField(max_length=64, unique=True)),
                ('target_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('transition_changed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=16)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('claim_token', models.UUIDField(blank=True, editable=False, null=True)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_category', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_delivery_events', to='listings.listing')),
                ('listing_price_alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_events', to='listings.listingpricealert')),
                ('price_transition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_delivery_events', to='listings.listingpricehistory')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_delivery_events', to=settings.AUTH_USER_MODEL)),
                ('saved_search', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_events', to='listings.savedsearch')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['notification_type', 'status', '-created_at'], name='notif_type_status_created_idx'), models.Index(fields=['recipient', '-created_at'], name='notif_recipient_created_idx'), models.Index(fields=['saved_search', 'status'], name='notif_search_status_idx'), models.Index(fields=['listing_price_alert', 'status'], name='notif_alert_status_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('status', 'processing'), _negated=True), models.Q(('claim_token__isnull', False), ('processing_started_at__isnull', False)), _connector='OR'), name='notif_processing_claim_required')],
            },
        ),
    ]
