# Generated by Django 5.2.15 on 2026-07-18 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0021_notification_delivery_preference_v288'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingpricehistory',
            name='reason',
            field=models.CharField(blank=True, choices=[('', 'No reason selected'), ('market_adjustment', 'Market adjustment'), ('promotion', 'Promotion'), ('condition_update', 'Condition update'), ('listing_correction', 'Listing correction'), ('other', 'Other')], default='', max_length=32),
        ),
    ]
