# Generated by Django 5.2.15 on 2026-07-19 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0022_listingpricehistory_reason_v292'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingpricehistory',
            name='discount_guardrail_status',
            field=models.CharField(blank=True, choices=[('', 'Eligible for public discount promotion'), ('raise_then_drop', 'Restricted after a recent price increase')], default='', max_length=32),
        ),
        migrations.AddField(
            model_name='listingpricehistory',
            name='discount_reference_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
