# Generated by Django 5.2.15 on 2026-07-20 16:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0023_listingpricehistory_discount_guardrail_v293'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationProviderOutcomeReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=64)),
                ('provider_event_id', models.CharField(max_length=255)),
                ('provider_message_id', models.CharField(max_length=255)),
                ('outcome', models.CharField(choices=[('delivered', 'Delivered'), ('bounced', 'Bounced'), ('complained', 'Complained')], max_length=16)),
                ('occurred_at', models.DateTimeField()),
                ('payload_digest', models.CharField(max_length=64)),
                ('matched_event_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-occurred_at', '-pk'],
            },
        ),
        migrations.AddField(
            model_name='notificationdeliveryevent',
            name='provider_event_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='notificationdeliveryevent',
            name='provider_message_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='notificationdeliveryevent',
            name='provider_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='notificationdeliveryevent',
            name='provider_outcome',
            field=models.CharField(blank=True, choices=[('delivered', 'Delivered'), ('bounced', 'Bounced'), ('complained', 'Complained')], max_length=16),
        ),
        migrations.AddField(
            model_name='notificationdeliveryevent',
            name='provider_outcome_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='notificationdeliveryevent',
            index=models.Index(fields=['provider_name', 'provider_message_id'], name='notif_provider_msg_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationprovideroutcomereceipt',
            index=models.Index(fields=['provider_name', 'provider_message_id'], name='notif_receipt_msg_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationprovideroutcomereceipt',
            index=models.Index(fields=['outcome', '-occurred_at'], name='notif_receipt_out_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationprovideroutcomereceipt',
            constraint=models.UniqueConstraint(fields=('provider_name', 'provider_event_id'), name='notif_provider_event_uniq'),
        ),
    ]
