# Generated by Django 5.2.15 on 2026-07-20 21:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0024_notification_provider_outcomes_v307'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationDeliveryRetentionEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('run_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cutoff_at', models.DateTimeField()),
                ('retention_days', models.PositiveIntegerField()),
                ('eligible_count', models.PositiveIntegerField()),
                ('candidate_count', models.PositiveIntegerField()),
                ('held_count', models.PositiveIntegerField(default=0)),
                ('non_terminal_count', models.PositiveIntegerField(default=0)),
                ('tombstoned_count', models.PositiveIntegerField()),
                ('batch_limit', models.PositiveIntegerField()),
                ('backup_policy', models.CharField(max_length=64)),
                ('evidence_digest', models.CharField(max_length=64, unique=True)),
                ('source', models.CharField(default='management_command', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.AddField(
            model_name='notificationdeliveryevent',
            name='legal_hold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationdeliveryevent',
            name='legal_hold_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='notificationdeliveryevent',
            name='legal_hold_set_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationdeliveryevent',
            name='legal_hold_set_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_delivery_legal_holds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationdeliveryevent',
            name='retention_tombstoned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationdeliveryevent',
            name='retention_evidence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_events', to='listings.notificationdeliveryretentionevidence'),
        ),
        migrations.AddIndex(
            model_name='notificationdeliveryevent',
            index=models.Index(fields=['legal_hold', 'retention_tombstoned_at', 'created_at'], name='notif_retention_scan_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationdeliveryevent',
            constraint=models.CheckConstraint(condition=models.Q(('legal_hold', False), models.Q(models.Q(('legal_hold_reason', ''), _negated=True), ('legal_hold_set_at__isnull', False)), _connector='OR'), name='notif_legal_hold_metadata'),
        ),
        migrations.AddConstraint(
            model_name='notificationdeliveryevent',
            constraint=models.CheckConstraint(condition=models.Q(('retention_tombstoned_at__isnull', True), ('retention_evidence__isnull', False), _connector='OR'), name='notif_retention_evidence_req'),
        ),
    ]
